### ISSUE TITLE
Depreciation in Django 4.0

### ISSUE THREAD

**Issue by shuki25** [jmichalicek/django-fractions#28]
I see you have patched this package to fix the depreciation issues in django 4.0 but you haven't pushed the patched code base to PyPI yet. My project depends on your package and I can't upgrade my project from django 3.2 to django 4.0 until then.

Thanks in advance!

**Comment by jmichalicek** [comment]
Sorry for the very slow response. I'm doing some cleanup over the next week and hope to push updates to pypi. I'm surprised every time I learn someone other than me is using this.
